/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(chiptosym.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(44c34303098648be80db6470df0da2c4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/advoqpsk/chiptosym.h>
// pydoc.h is automatically generated in the build directory
#include <chiptosym_pydoc.h>

void bind_chiptosym(py::module& m)
{

    using chiptosym    = ::gr::advoqpsk::chiptosym;


    py::class_<chiptosym, gr::block, gr::basic_block,
        std::shared_ptr<chiptosym>>(m, "chiptosym", D(chiptosym))

        .def(py::init(&chiptosym::make),
           D(chiptosym,make)
        )
        



        ;




}








